sudo: false
language: node_js
node_js: '14'
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # needed by nodegit (repo-cooker)
      - libstdc++-4.9-dev
git:
  depth: 9999
notifications:
  email: false
script:
  - |
    if [[ $SKIP_TESTS != 'true' ]]; then
      npm run link
      npm run checkdeps
      # npm run lint
      # npm run test
      npm run build
    fi
after_success:
  - |
    if [[ $TRAVIS_SECURE_ENV_VARS == 'true' ]]; then
      git remote set-url origin https://pawi-bot:${GH_TOKEN}@github.com/pawijs/pawi
      git config --global user.email "maia@pawijs.org"
      git config --global user.name "Maia Taewana"
    fi
    if [[ $TRAVIS_BRANCH == 'master' || $TRAVIS_BRANCH == 'next' ]] && [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
      printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN\n" > ~/.npmrc
      printf "$VSCE_TOKEN\n" > ~/.vsce
      npm install -g vsce
      # npm install --no-save nodegit
      npm run release
    fi
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
